version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn install
      - run: bundle install
      - run: MYAPP_CONFIG=prod bundle exec fastlane android ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - android