version: 2
jobs:
  android:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn install
      - run: MYAPP_KEYSTORE_PASSWORD=123khoa@ MYAPP_CONFIG=prod yarn fastlane:android-ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - android